name: CI

on:
  push:
    branches: [master]
    paths_ignore: ["**.md"]
  pull_request:
    paths_ignore: ["**.md"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Test the plugin
      uses: asdf-vm/actions/plugin-test@v1
      with:
        version: ${{ matrix.version }}
        command: cmctl version --client
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make lint
